### ISSUE TITLE
Text not arranged correctly when text contain new line

### ISSUE THREAD

**Issue by apinprastya** [Cretezy/flutter_linkify#1]
So, when the text contains new lines the text is not correctly arrange. 
This text work perfect : 
`[text] [text with url] [text]`

But this one not : 
`[text] [newline] [text with url] [newline] [text]`

**Comment by Cretezy** [comment]
Can you provide the code for each of your examples, and screenshots of the results?

**Comment by apinprastya** [comment]
Hi @Cretezy, sorry for late reply. You can reproduce the bug by edit the example :
please check https://github.com/Cretezy/flutter_linkify/blob/master/example/lib/main.dart#L25

And change the line with this line : 
`text: "Made by\nhttps://cretezy.com \n Hi Again",`

**Comment by Cretezy** [comment]
Fixed! I just published v1.0.2. Thanks for the report!

**Comment by apinprastya** [comment]
Hi @Cretezy , it still happening.
![screenshot from 2018-11-07 06-59-06](https://user-images.githubusercontent.com/1171479/48102223-afda7b80-e25c-11e8-876c-1fa8aab446f3.png)

**Comment by apinprastya** [comment]
That freshly new clone from github. First I try on my project and update the version to 1.0.2, but it still happening, and then I clone it from github and run the example in case I have problem with my project. But it also happen on example

**Comment by Cretezy** [comment]
Alright I'll take another look when I get home. Not too sure what's going on

**Comment by Cretezy** [comment]
Alright pushed v1.0.3 with the fix for this! Was using `\s?` instead of `\s*?` for matching whitespace. Let me know how it is!

**Comment by apinprastya** [comment]
Hi again @Cretezy, the bug still occure when I have several new lines.
![screenshot from 2018-11-10 09-35-18](https://user-images.githubusercontent.com/1171479/48296674-63957280-e4cc-11e8-9619-a961a188f701.png)

**Comment by huulbaek** [comment]
I'm experiencing the same as @apinprastya – any news on this? Or is the issue really closed?

(thanks for the great contribution, btw)

**Comment by Cretezy** [comment]
Hey sorry, haven't gotten to fixing this. I'll take a look into it now.

**Comment by Cretezy** [comment]
Update:

![image](https://user-images.githubusercontent.com/2672503/53054844-c0ada680-3473-11e9-9bcd-06be35f5406e.png)

Pushed out v1.0.4 with the update.

**Comment by voivoed** [comment]
I'm having the same issue, multiple links with \n, only the link on the first line gets humanized (I wrapped the Linkify widget creation in a function): 

_makeLink(
  context,
  "Freepik at https://www.freepik.com/\n"
  "Daniel Bruce at http://www.entypo.com\n"
  "Aristeides Stathopoulos at http://aristeides.com/\n"
  "Smashing Magazine at http://designmodo.com/linecons-free/\n"
  "Dave Gandy at http://fortawesome.github.com/Font-Awesome/"),

Widget _makeLink(BuildContext context, String textToLink) {
  return Linkify(
    onOpen: (url) async {
      if (await canLaunch(url)) {
        await launch(url);
      } else {
        throw 'Could not launch $url';
      }
    },
    text: textToLink,
    style: TextStyle(color: Theme.of(context).hintColor),
    linkStyle: TextStyle(color: Theme.of(context).primaryColor),
    humanize: true,
  );
}

Returns: 

![capture](https://user-images.githubusercontent.com/48135618/53659302-39a5be80-3c29-11e9-869e-974b061fc030.JPG)

**Comment by Cretezy** [comment]
@voivoed I'm not too sure what's wrong with the code you presented.

Are you on the latest version?

Can you give a full code example I can run, and the expected vs actual results?

**Comment by voivoed** [comment]
@Cretezy  I'm using the latest version, just created a simple project to test it.

```dart
import 'package:flutter/material.dart';
import 'package:flutter_linkify/flutter_linkify.dart';

void main() {
  runApp(
    MaterialApp(
      title: "Linkify Test",
      home: Home(),
    ),
  );
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Linkify Test"),
      ),
      body: Center(
        child: Linkify(
          onOpen: (url) => print("Clicked $url!"),
          text: "Made by https://cretezy.com\n"
              "Hosted by https://github.com\n"
              "For use with Flutter https://flutter.io",
          humanize: true,
        ),
      ),
    );
  }
}
```

When I run it, the first "https//" (from cretezy.com) gets removed as per the "humanize" parameter, but the next 2 (github and flutter) stay there. Here's a screenshot:

![capture](https://user-images.githubusercontent.com/48135618/53666003-f18f9780-3c3a-11e9-96b6-488f91eaa552.JPG)

**Comment by Cretezy** [comment]
Ah yes, that's definitely a bug. I'll take a look soon. We'll track this in another issue though since it's related to this

**Comment by Cretezy** [comment]
@voivoed Fixed in v1.1.1! What a very simple fix

**Comment by voivoed** [comment]
@Cretezy it's working now, thanks!
